# Copyright (c) 2014-2022 Michael Stauber, SOLARSPEED.NET
# Copyright (c) 2014-2022 Team BlueOnyx, BLUEONYX.IT
# $Id: support.conf

System.Support.bugreport_trigger		exec:base/support/bugreport.pl		EXECUTE
System.Support.ticket_trigger			exec:base/support/ticket.pl			EXECUTE

