# $Id: test.conf
# Test configuration file

Foo._CREATE	perl:/usr/sausalito/handlers/base/sauce-basic/testhandler	EXECUTE
Foo._DESTROY	perl:/usr/sausalito/handlers/base/sauce-basic/testhandler	EXECUTE
Foo.*		perl:/usr/sausalito/handlers/base/sauce-basic/testhandler	EXECUTE

