unix_socket_path = /usr/sausalito/cced.socket
socket_read_timeout = 300
listen_address = 127.0.0.1:9092
cert_file = /etc/cced-api/certs/certificate
key_file = /etc/cced-api/certs/key
ca_cert_file = /etc/cced-api/certs/ca-certs
enable_http = false
logging = true
debuglog = false
api_access =
token_lifetime = 300
api_auth_fails = 5
api_ban_time = 60