#!/usr/bin/perl
#
# Author: Kevin K.M. Chiu
# $Id: syncServer

# This is a script that refreshes this BlueLinQ server by synchronizing PKGs
# from other BlueLinQ servers.
# To use, make sure the variables below are correct, run it manually or drop
# this file to a cron directory so that it can run periodically.

use strict;

# make sure this is a space separated list of upper level BlueLinQ servers
my $serverUrls = 'http://10.9.25.66/packages';

# make sure this is where the utilities are located
my $utilDir = '/root/base-swupdate.mod/glue/sbin';

# make sure this is where all PKG files and the package information file are
# located. This must be a web accessible directory
my $pkgDir = '/home/users/admin/web';

# make sure this is the URL of the directory as defined in $pkgDir
my $pkgUrl = 'http://10.9.25.66/~admin';

# make sure this is the name of the package information file
my $infoName = 'packages';

# make sure these are the right proxies
my $ftpProxy = '';
my $httpProxy = '';

system("$utilDir/downloadPkgs -d \"$pkgDir\" -f \"$ftpProxy\" -w \"$httpProxy\" $serverUrls");
system("$utilDir/makeServer -d \"$pkgDir\" -o \"$pkgDir/$infoName\" -u \"$pkgUrl\" -f");

# 
# Copyright (c) 2008-2022 Michael Stauber, SOLARSPEED.NET
# Copyright (c) 2008-2022 Team BlueOnyx, BLUEONYX.IT
# Copyright (c) 2003 Sun Microsystems, Inc. 
# All Rights Reserved.
# 
# 1. Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
#    notice, this list of conditions and the following disclaimer in 
#    the documentation and/or other materials provided with the 
#    distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its 
#    contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
# You acknowledge that this software is not designed or intended for 
# use in the design, construction, operation or maintenance of any 
# nuclear facility.
# 