#!/usr/bin/perl
#
# This script creates <VirtualHost> containers for default sites on the fly.
# It creates *-placeholder sites and one for each bound IPv4 and IPv6 IP.
# For the HTTPS VirtualHosts it uses the AdmServ SSL certificate.
#
# It also can block bad user-agents from accessing URLs and may return custom
# robots.txt if Vsites don't have their own robots.txt
#
# Lastly: If a Vsite is suspended, it will create a new <VirtualHost> container
# for HTTP and one for SSL (if SSL is enabled) that points the DocumentRoot to
# /var/www/html and it disallows access to all pages but suspended.html. This
# page is localized in all GUI messages and shows that the Vsite has been
# suspended. If a suspension reason was given, then that will be shown as well.
#

$DEBUG = "0";

use Apache2::ServerUtil();
use lib qw(/usr/sausalito/perl);

use CCE;
use Sauce::Service;

$cce = new CCE;
$cce->connectuds();

($oid) = $cce->find('System');
($ok, $System) = $cce->get($oid);

# Get Server FQDN:
$System_FQDN = $System->{'hostname'} . '.' . $System->{'domainname'};

# Write /var/www/html/fqdn.json for suspended.html:
open(my $fh, '>', "/var/www/html/fqdn.json");
print $fh qq|{ "fqdn": "$System_FQDN" }\n|;
close($fh);

# Check if $System_FQDN starts with "localhost"
if ($System_FQDN =~ /^localhost/) {
    # Replace $System_FQDN with the web server IP from the environment
    $System_FQDN = $ENV{'SERVER_ADDR'};
}

# Get "System" . "Web":
($ok, $objWeb) = $cce->get($oid, 'Web');

($ok, $objNginx) = $cce->get($oid, 'Nginx');

# Get "System" . "SSL":
($ok, $objSSL) = $cce->get($oid, 'SSL');

# Check if we're using our custom /etc/httpd/conf.d/php.conf:
$custom_php_conf = `cat /etc/httpd/conf.d/php.conf |grep "Please note: BlueOnyx 5210R sets all PHP related"|wc -l`;
chomp($custom_php_conf);
if ($custom_php_conf ne "1") {
  if (-f "$confdir/php.conf.bx") {
    system("cp $confdir/php.conf.bx $confdir/php.conf");
  }
  else {
    open(my $fh, '>', '/etc/httpd/conf.d/php.conf');
    print $fh "# Please note: BlueOnyx 5210R sets all PHP related options\n";
    print $fh "# in the Vsite include files. Please do not edit this file\n";
    print $fh "# to add custom options, as they will be deleted.\n";
    close $fh;
  }
  system("chown root:root /etc/httpd/conf.d/php.conf");
  Sauce::Service::service_run_init('httpd', 'reload');
}

# Find out if we do have a CA-Cert:
@ca_certs = $cce->scalar_to_array($objSSL->{caCerts});
$CALine = '';
if ( -f "/etc/admserv/certs/ca-certs") {
    $check = `cat /etc/admserv/certs/ca-certs |grep 'BEGIN CERTIFICATE-'|wc -l`;
    chomp($check);
    if ($check eq "1") {
        # We do have intermediate(s). Use it:
        $CALine = 'SSLCACertificateFile  /etc/admserv/certs/ca-certs';
    }    
}

# Server-Name:
$ServerName = $System->{hostname} . '.' . $System->{domainname};

# HTTP and SSL ports:
$httpPort = "80";
if ($objWeb->{'httpPort'}) {
    $httpPort = $objWeb->{'httpPort'};
}
$sslPort = "443";
if ($objWeb->{'sslPort'}) {
    $sslPort = $objWeb->{'sslPort'};
}

# Set up default error pages:
if ((!-d '/var/www/html/error') || (!-f '/var/www/html/error/suspended.html') || (!-f '/var/www/html/error/502-bad-gateway.html')) {
    system("mkdir /var/www/html/error");
    system("cp /etc/skel/vsite/en/web/error/*.html /var/www/html/error/")
}

$CipherLine = "        SSLProtocol -all +TLSv1.3 +TLSv1.2\n";
$CipherLine .= "        SSLCipherSuite    TLSv1.3   TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256\n";
$CipherLine .= "        SSLCipherSuite    SSL       ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:EECDH+AESGCM:EDH+AESGCM\n";
$CipherLine .= "        SSLOpenSSLConfCmd Curves X25519:secp521r1:secp384r1:prime256v1\n";
$CipherLine .= "        SSLHonorCipherOrder On\n";

# GUI may run on different ports and the admin URLs may be nonstandard. We pull them from CODB and use them:
$GUI_PORT = $System->{'GUI_PORT'};
@GUI_URLs = $cce->scalar_to_array($System->{'GUI_URLs'});

$gui_url_rewrites = "RewriteEngine On\n";

# Always add the forbidden rule (it doesn't depend on GUI_URLs)
$gui_url_rewrites .= 'RewriteCond %{HTTP_HOST} ^([^:]+)' . "\n";
$gui_url_rewrites .= 'RewriteCond %{DOCUMENT_ROOT} !-d' . "\n";
$gui_url_rewrites .= 'RewriteRule .* https://%1:' . $GUI_PORT . '/gui/Forbidden403 [L,R]' . "\n";

# Only add per-URI rules if we actually have entries
if (@GUI_URLs) {
    foreach my $uri (@GUI_URLs) {
        next unless $uri;                    # skip empty strings
        if ($System->{'GUIredirects'} eq '1') {
            $gui_url_rewrites .= 'RewriteCond %{HTTP_HOST} ^([^:]+)' . "\n";
            $gui_url_rewrites .= 'RewriteRule ^/' . $uri . '/?$ https://' . $System_FQDN . ':' . $GUI_PORT . '/login [L,R]' . "\n";
        }
        else {
            $gui_url_rewrites .= 'RewriteCond %{HTTP_HOST} ^([^:]+)' . "\n";
            $gui_url_rewrites .= 'RewriteRule ^/' . $uri . '/?$ https://%1:' . $GUI_PORT . '/login [L,R]' . "\n";
        }
    }
}

# Bot protection and robots.txt handling:
$robots_and_badbots_config = '';
if (($objWeb->{'xmlrpc_deny'} eq '1') || ($objWeb->{'bad_useragents_deny'} eq '1') || ($objWeb->{'default_robots_txt'} eq '1')) {

    $botconfig_header = "    # Combined Apache Configuration for Bot Blocking and Conditional robots.txt\n";
    $botconfig_header .= "    <IfModule mod_rewrite.c>\n";
    $botconfig_header .= "        RewriteEngine On\n";

    $botconfig_footer = "    </IfModule>";

    $XMLRPC_HANDLING = '';
    if ($objWeb->{'xmlrpc_deny'} eq '1') {
        $XMLRPC_HANDLING .= "\n";
        $XMLRPC_HANDLING .= '        # Block xmlrpc.php access' . "\n";
        $XMLRPC_HANDLING .= '        RewriteCond %{REQUEST_URI} ^/xmlrpc\.php$ [NC]' . "\n";
        $XMLRPC_HANDLING .= '        RewriteRule ^.*$ - [F,L]' . "\n";
    }

    # Extract chunks for user-agent matching (moved here so available for robots and block rules)
    my @chunks;
    if ($objWeb->{'bad_useragents_deny'} eq '1') {
        @bad_useragents = $cce->scalar_to_array($objWeb->{bad_useragents});
        @good_useragents = $cce->scalar_to_array($objWeb->{good_useragents});

        if (@bad_useragents) {
            my $chunk_size = 10;  # Adjust this to keep regex manageable
            while (@bad_useragents) {
                push @chunks, join('|', splice(@bad_useragents, 0, $chunk_size));
            }
        }
    }

    $robots_line = '';
    if ($objWeb->{'default_robots_txt'} eq '1') {
        $robots_line .= "\n";
        $robots_line .= "        # Conditional robots.txt handling\n";

        if (@chunks && ($objWeb->{'bad_useragents_deny'} eq '1')) {
            $robots_line .= "        # If the request is for /robots.txt and the visitor is an unwanted bot, serve the global one that denies all crawlers:\n";
            $robots_line .= "        RewriteCond \%{REQUEST_URI} ^/robots\\.txt\$ [NC]\n";
            foreach my $chunk (@chunks) {
                $robots_line .= "        RewriteCond \%{HTTP_USER_AGENT} \"($chunk)\" [NC,OR]\n";
            }
            $robots_line =~ s/\[NC,OR\]$/\[NC\]/;  # Remove last OR
            $robots_line .= "        RewriteRule ^/robots\\.txt\$ /var/www/html/robots_deny_all.txt [L]\n";
            $robots_line .= "\n";
            $robots_line .= "        # If the request is for /robots.txt, check if the site's robots.txt exists\n";
            $robots_line .= "        RewriteCond \%{REQUEST_URI} ^/robots\\.txt\$ [NC]\n";
            $robots_line .= "        RewriteCond \%{DOCUMENT_ROOT}/robots.txt -f\n";
            $robots_line .= "        RewriteRule ^/robots\\.txt\$ - [L]\n";
            $robots_line .= "\n";
        }
        $robots_line .= "        # If no site-specific robots.txt exists, fall back to the global one\n";
        $robots_line .= "        RewriteCond \%{REQUEST_URI} ^/robots\\.txt\$ [NC]\n";
        $robots_line .= "        RewriteCond \%{DOCUMENT_ROOT}/robots.txt !-f\n";
        $robots_line .= "        RewriteRule ^/robots\\.txt\$ /var/www/html/robots.txt [L]\n";
        $robots_line .= "\n";
    }

    $BOT_HANDLING = '';
    if (@chunks && ($objWeb->{'bad_useragents_deny'} eq '1')) {
        $BOT_HANDLING .= "\n";
        $BOT_HANDLING .= "        # Block unwanted bot traffic by User-Agent\n";
        foreach my $chunk (@chunks) {
            $BOT_HANDLING .= "        RewriteCond \%{HTTP_USER_AGENT} \"($chunk)\" [NC,OR]\n";
        }
        $BOT_HANDLING =~ s/\[NC,OR\]$/\[NC\]/;  # Remove last OR
        $BOT_HANDLING .= "        RewriteCond \%{REQUEST_URI} !^/error/ [NC]\n";  # Allow access to error pages
        $BOT_HANDLING .= "        RewriteRule .* - [F,L]\n";
    }

    # Assemble the results:
    $robots_and_badbots_config .= $botconfig_header;
    $robots_and_badbots_config .= $XMLRPC_HANDLING;
    $robots_and_badbots_config .= $robots_line;  # Moved before BOT_HANDLING for priority on /robots.txt
    $robots_and_badbots_config .= $BOT_HANDLING;
    $robots_and_badbots_config .= $botconfig_footer;
}

# Generate config on the fly:
$config = '';
$config = <<CONFIG;
    #NameVirtualHost *:$httpPort
    #NameVirtualHost *:$sslPort
CONFIG

# Only include Listen 443 if Nginx proxy is NOT enabled:
if ($objNginx->{enabled} ne '1') {
    $config .= "    Listen $sslPort https\n";
}

$config .= <<CONFIG;

$gui_url_rewrites

$CipherLine

    SSLStrictSNIVHostCheck off
    SSLCompression off
    
    SSLUseStapling          on
    SSLStaplingResponderTimeout 5
    SSLStaplingReturnResponderErrors off
    SSLStaplingCache        shmcb:/var/run/ocsp(128000)

    SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire

$robots_and_badbots_config

    <VirtualHost *:$httpPort>
        ServerName $ServerName
        ServerAdmin admin
        DocumentRoot /var/www/html/

        ErrorDocument 401 /error/401-authorization.html
        ErrorDocument 403 /error/403-forbidden.html
        ErrorDocument 404 /error/404-file-not-found.html
        ErrorDocument 500 /error/500-internal-server-error.html
    </VirtualHost>

    <VirtualHost *:$sslPort>
        ServerName $ServerName
        SSLengine on

$CipherLine

        SSLCompression off

        # Server Certificate:
        $CALine
        SSLCertificateFile    /etc/admserv/certs/certificate
        SSLCertificateKeyFile /etc/admserv/certs/key
        ServerAdmin admin
        DocumentRoot /var/www/html

        ErrorDocument 401 /error/401-authorization.html
        ErrorDocument 403 /error/403-forbidden.html
        ErrorDocument 404 /error/404-file-not-found.html
        ErrorDocument 500 /error/500-internal-server-error.html
    </VirtualHost>
CONFIG

# Note: Presence of the file '/etc/sysconfig/guissl' will disable default Vsite for all IPs:
if (! -f '/etc/sysconfig/guissl') {
    # Get all IPs:
    @arr_assigned_ipv4 = split (/\n/, `LC_ALL=C /sbin/ip address show |grep inet|grep global|awk -F "inet " '{print \$2}'|awk -F " brd " '{print \$1}'|cut -d / -f1|sed '/^\$/d'`);
    @arr_assigned_ipv6 = split (/\n/, `LC_ALL=C /sbin/ip address show |grep inet|grep global|awk -F "inet6 " '{print \$2}'|awk -F " brd " '{print \$1}'|cut -d / -f1|sed '/^\$/d'`);
}
else {
    @arr_assigned_ipv4 = ();
    @arr_assigned_ipv6 = ();
}

foreach $x (@arr_assigned_ipv4) {
    $config .= <<CONFIG;
    <VirtualHost $x:$httpPort>
        ServerName $ServerName
        ServerAdmin admin
        DocumentRoot /var/www/html

        ErrorDocument 401 /error/401-authorization.html
        ErrorDocument 403 /error/403-forbidden.html
        ErrorDocument 404 /error/404-file-not-found.html
        ErrorDocument 500 /error/500-internal-server-error.html
    </VirtualHost>

    <VirtualHost $x:$sslPort>
        ServerName $ServerName
        SSLengine on
        SSLCompression off

$CipherLine

        # Server Certificate:
        $CALine
        SSLCertificateFile    /etc/admserv/certs/certificate
        SSLCertificateKeyFile /etc/admserv/certs/key
        ServerAdmin admin
        DocumentRoot /var/www/html

        ErrorDocument 401 /error/401-authorization.html
        ErrorDocument 403 /error/403-forbidden.html
        ErrorDocument 404 /error/404-file-not-found.html
        ErrorDocument 500 /error/500-internal-server-error.html
    </VirtualHost>
CONFIG
}

foreach $z (@arr_assigned_ipv6) {
    $config .= <<CONFIG;
    <VirtualHost [$z]:$httpPort>
        ServerName $ServerName
        ServerAdmin admin
        DocumentRoot /var/www/html/

        ErrorDocument 401 /error/401-authorization.html
        ErrorDocument 403 /error/403-forbidden.html
        ErrorDocument 404 /error/404-file-not-found.html
        ErrorDocument 500 /error/500-internal-server-error.html
    </VirtualHost>

    <VirtualHost [$z]:$sslPort>
        ServerName $ServerName
        SSLengine on
        SSLCompression off

$CipherLine

        # Server Certificate:
        $CALine
        SSLCertificateFile    /etc/admserv/certs/certificate
        SSLCertificateKeyFile /etc/admserv/certs/key
        ServerAdmin admin
        DocumentRoot /var/www/html

        ErrorDocument 401 /error/401-authorization.html
        ErrorDocument 403 /error/403-forbidden.html
        ErrorDocument 404 /error/404-file-not-found.html
        ErrorDocument 500 /error/500-internal-server-error.html
    </VirtualHost>
CONFIG
}

# Get suspended Vsites:
@suspended_sites = $cce->findx('Vsite', { 'suspend' => '1' });
foreach my $vsite_oid (@suspended_sites) {

    ($ok, my $vsite) = $cce->get($vsite_oid);
    if (!$ok) {
        print STDERR "Failed to get Vsite object for OID $vsite_oid\n";
        next;
    }

    $vsite_ip = $vsite->{'ipaddr'};
    $fqdn = $vsite->{'fqdn'};
    @webAliases = $cce->scalar_to_array($vsite->{'webAliases'});
    $aliasLine = '    ';
    if (@webAliases && grep { $_ ne '' } @webAliases) {
        $aliasLine = '    ServerAlias ' . join(' ', @webAliases);
    }

    $vsite_Basedir = $vsite->{'basedir'};
    $vsite_CertDir = $vsite_Basedir . '/wwwroot/certs';

    # HTTP:
$config .= <<CONFIG;
    <VirtualHost $vsite_ip:$httpPort>
    Protocols h2 http/1.1
    ServerName $fqdn
    $aliasLine

    ServerAdmin admin
    DocumentRoot /var/www/html/
    ErrorDocument 401 /error/401-authorization.html
    ErrorDocument 403 /error/403-forbidden.html
    ErrorDocument 404 /error/404-file-not-found.html
    ErrorDocument 500 /error/500-internal-server-error.html

$robots_and_badbots_config

    <IfModule mod_headers.c>
        Header set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
        Header set Pragma "no-cache"
        Header set Expires 0
    </IfModule>

    RewriteEngine on
    RewriteOptions inherit
    RewriteCond \%{REQUEST_URI} !^/error/suspended.html\$ [NC]
    RewriteCond \%{REQUEST_URI} !^/.elm/ [NC]
    RewriteCond \%{REQUEST_URI} !^/fqdn.json\$ [NC]
    RewriteRule ^.*\$ /error/suspended.html [L]
    <IfModule mod_userdir.c>
       UserDir disabled
    </IfModule>
    </VirtualHost>
CONFIG

    # HTTPS:
    ($ok, my $vsite_SSL) = $cce->get($vsite_oid, 'SSL');
    if (!$ok) {
        print STDERR "Failed to get Vsite . SSL object for OID $vsite_oid\n";
        next;
    }

    if (($vsite_SSL->{'enabled'} eq "1") && (-f "$vsite_CertDir/certificate") && (-f "$vsite_CertDir/key")) {

        $vsite_Basedir = $vsite->{'basedir'};
        $vsite_CertDir = $vsite_Basedir . '/wwwroot/certs';

        $CipherLine = "        SSLProtocol -all +TLSv1.3 +TLSv1.2\n";
        $CipherLine .= "        SSLCipherSuite    TLSv1.3   TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256\n";
        $CipherLine .= "        SSLCipherSuite    SSL       ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:EECDH+AESGCM:EDH+AESGCM\n";
        $CipherLine .= "        SSLOpenSSLConfCmd Curves X25519:secp521r1:secp384r1:prime256v1\n";
        $CipherLine .= "        SSLHonorCipherOrder On\n";

        # Find out if we do have a CA-Cert:
        @ca_certs = $cce->scalar_to_array($vsite_SSL->{caCerts});
        $CALine = '';
        if ( -f "$vsite_CertDir/ca-certs") {
            $check = `cat $vsite_CertDir/ca-certs |grep 'BEGIN CERTIFICATE-'|wc -l`;
            chomp($check);
            if ($check eq "1") {
                # We do have intermediate(s). Use it:
                $CALine = "SSLCACertificateFile  $vsite_CertDir/ca-certs";
            }    
        }

$config .= <<CONFIG;
    <VirtualHost $vsite_ip:$sslPort>
    Protocols h2 http/1.1
    ServerName $fqdn
    $aliasLine

    SSLengine on
    SSLCompression off

$CipherLine

    # Server Certificate:
    $CALine
    SSLCertificateFile    $vsite_CertDir/certificate
    SSLCertificateKeyFile $vsite_CertDir/key

    ServerAdmin admin
    DocumentRoot /var/www/html/
    ErrorDocument 401 /error/401-authorization.html
    ErrorDocument 403 /error/403-forbidden.html
    ErrorDocument 404 /error/404-file-not-found.html
    ErrorDocument 500 /error/500-internal-server-error.html

$robots_and_badbots_config

    <IfModule mod_headers.c>
        Header set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
        Header set Pragma "no-cache"
        Header set Expires 0
    </IfModule>

    RewriteEngine on
    RewriteOptions inherit
    RewriteCond \%{REQUEST_URI} !^/error/suspended.html\$ [NC]
    RewriteCond \%{REQUEST_URI} !^/.elm/ [NC]
    RewriteCond \%{REQUEST_URI} !^/fqdn.json\$ [NC]
    RewriteRule ^.*\$ /error/suspended.html [L]
    <IfModule mod_userdir.c>
       UserDir disabled
    </IfModule>
    </VirtualHost>
CONFIG
    }
}

# For debugging:
if ($DEBUG) {
    open($fh, '>', '/tmp/httpd.debug');
    print $fh $config;
    close $fh;
}

#
### If Nginx SSL-Proxy is enabled, strip all :443-related <VirtualHost> entries.
#

if ($objNginx->{enabled} eq '1') {
    my @lines = split(/\n/, $config);
    my @filtered;
    my $inside_ssl_vhost = 0;

    foreach my $line (@lines) {
        if ($line =~ /^\s*<VirtualHost\s+[^>]*:$sslPort>/ || $line =~ /^\s*<VirtualHost\s+\[[^\]]+\]:$sslPort>/) {
            $inside_ssl_vhost = 1;
            next;
        }
        if ($inside_ssl_vhost && $line =~ /^\s*<\/VirtualHost>/) {
            $inside_ssl_vhost = 0;
            next;
        }
        next if $inside_ssl_vhost;
        push @filtered, $line;
    }

    $config = join("\n", @filtered);

    # For debugging:
    if ($DEBUG) {
        open($fh, '>', '/tmp/nginx.debug');
        print $fh $config;
        close $fh;
    }
}

# Push out config:
$server = Apache2::ServerUtil->server;
$server->add_config([split /\n/, $config]);

$cce->bye('SUCCESS');

1;

# 
# Copyright (c) 2018-2025 Michael Stauber, SOLARSPEED.NET
# Copyright (c) 2018-2025 Team BlueOnyx, BLUEONYX.IT
# All Rights Reserved.
# 
# 1. Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
#    notice, this list of conditions and the following disclaimer in 
#    the documentation and/or other materials provided with the 
#    distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its 
#    contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
# You acknowledge that this software is not designed or intended for 
# use in the design, construction, operation or maintenance of any 
# nuclear facility.
# 
