#
### Email Autoconfigure Proxy settings:
#

ProxyRequests Off
ProxyPreserveHost On

SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerName off
SSLProxyCheckPeerCN off
SSLProxyCheckPeerExpire off

RewriteEngine On

# Only proxy these endpoints when accessed via autoconfig.* or autodiscover.*
RewriteCond %{HTTP_HOST} ^autoconfig\. [NC,OR]
RewriteCond %{HTTP_HOST} ^autodiscover\. [NC]

# Thunderbird Autoconfig
RewriteRule ^/mail/config-v1\.1\.xml$ https://127.0.0.1:81/autoconfig/mail/config-v1.1.xml [P,L,QSA,NE]

RewriteRule ^/\.well-known/autoconfig/mail/config-v1\.1\.xml$ https://127.0.0.1:81/autoconfig/mail/config-v1.1.xml [P,L,QSA,NE]

# Outlook Autodiscover
RewriteRule ^/autodiscover/autodiscover\.xml$ https://127.0.0.1:81/autodiscover/autodiscover.xml [P,L,NE]

# Outlook (Classic) probing for ActiveSync/Z-Push
#RewriteRule ^/autodiscover/autodiscover\.json/v1\.0/.*$ https://127.0.0.1:81/autodiscover/autodiscover.json/v1.0/$0 [P,L,NE]
#RewriteRule ^/autodiscover/autodiscover\.json/v1\.0/(.*)$ https://127.0.0.1:81/autodiscover/autodiscover.json/v1.0/$1 [P,L,NE]

# Content types + caching
<LocationMatch "^/(mail/config-v1\.1\.xml|\.well-known/autoconfig/mail/config-v1\.1\.xml)$">
    Header always set Content-Type "application/xml; charset=utf-8"
    Header always set Cache-Control "no-store"
</LocationMatch>

<Location "/autodiscover/autodiscover.xml">
    Header always set Content-Type "text/xml; charset=utf-8"
    Header always set Cache-Control "no-store"
</Location>
