# Global Error Pages Configuration in case Vsite is missing /wwwroot/web/error/:

# Check if the VirtualSite's error page exists, otherwise fall back to the global error directory
ErrorDocument 401 /fallback-error/401-authorization.html
ErrorDocument 403 /fallback-error/403-forbidden.html
ErrorDocument 404 /fallback-error/404-file-not-found.html
ErrorDocument 500 /fallback-error/500-internal-server-error.html
ErrorDocument 502 /fallback-error/502-bad-gateway.html

# Alias for fallback error pages
Alias /fallback-error/ "/var/www/html/error/"

<Directory "/var/www/html/error">
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

# Disable directory listing for /usr/share/httpd/icons/:
<Directory /usr/share/httpd/icons/>
Options -Indexes
</Directory> 

# Turn off Apache debugging support for TRACK/TRACE:
TraceEnable off

# Don't let the whole world know which modules we're running:
ServerTokens ProductOnly

# Logging:
LogFormat "%v %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%v %{X-Real-IP}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
SetEnvIf X-Real-IP "^.*\..*\..*\..*" forwarded
CustomLog "/var/log/httpd/access_log" combined env=!forwarded
CustomLog "/var/log/httpd/access_log" proxy env=forwarded

# For Vsite error pages in Elmer Style:
Alias /.elm /usr/sausalito/ui/web/.elm
<Directory "/usr/sausalito/ui/web/.elm">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
