/var/named/chroot/var/log/* {
    missingok
    daily
    rotate 0
    shred
    maxage 7
    missingok
    minsize 500
    su named named
    create 0644 named named
    postrotate
        /usr/bin/systemctl reload named-chroot.service > /dev/null 2>&1 || true
    endscript
}
