# $Id: remote.conf
# Copyright (c) 2008-2023 Michael Stauber, SOLARSPEED.NET
# Copyright (c) 2008-2023 Team BlueOnyx, BLUEONYX.IT
# All Rights Reserved.

# Toggle service:
System._CREATE                        perl:base/organizer/toggle_radicale.pl
System.Radicale.*                     perl:base/organizer/toggle_radicale.pl

# Fire on User-Delete:
User._DESTROY                         perl:base/organizer/userdata_remove.pl 

# Fire on Backup/Restore:
User.Radicale.backup                  perl:base/organizer/user_backup.pl 
User.Radicale.restore                 perl:base/organizer/user_restore.pl 

# AM stuff
ActiveMonitor.Radicale.enabled        perl:base/am/am_enabled.pl EXECUTE
ActiveMonitor.Radicale.monitor        perl:base/am/am_enabled.pl EXECUTE
System.Radicale.enabled               perl:base/organizer/enableAM.pl

