#!/usr/bin/expect
# $Id $
source /usr/sausalito/swatch/statecodes.tcl

if {![info exists env(redMsg)] || $env(redMsg) eq ""} {
    set env(redMsg) {[[base-email.amSMTPAuthNotRunning]]}
}
if {![info exists env(greenMsg)] || $env(greenMsg) eq ""} {
    set env(greenMsg) {[[base-email.amSMTPAuthStatusOK]]}
}

# don't echo the dialog
log_user 0

# we use telnet to connect
spawn /usr/sausalito/swatch/bin/check-sasl.sh
expect {
    "is running..." {}
    default { # we don't connect properly
        # try to restart
        # use catch so we don't report errors on the exec,
        # only on the dialog itself
        catch {exec systemctl restart saslauthd >&/dev/null} result
        sleep 5
        # redo test, fail if get an error again
        # spawn /sbin/service saslauthd status
        spawn /usr/sausalito/swatch/bin/check-sasl.sh
        expect {
            "is running..." {}
            default {
                puts -nonewline $env(redMsg);
                flush stdout;
                exit $AM_STATE_RED;
            }
        }
    }
}
puts -nonewline $env(greenMsg)
flush stdout;
exit $AM_STATE_GREEN
