# phpMyAdmin - Web based MySQL browser written in php
# 

Redirect 301 /phpMyAdmin /base/phpMyAdmin/index.php

# This directory does not require access over HTTP - taken from the original
# phpMyAdmin upstream tarball
#

<Directory /usr/sausalito/ui/web/base/phpMyAdmin>
    CGIPassAuth on
    DirectoryIndex index.php
</Directory>

<Directory /usr/sausalito/ui/web/base/phpMyAdmin/libraries>
    Order Deny,Allow
    Deny from All
    Allow from None
</Directory>

# This configuration prevents mod_security at phpMyAdmin directories from
# filtering SQL etc.  This may break your mod_security implementation.
#
#<IfModule mod_security.c>
#    <LocationMatch "/phpMyAdmin/(.+)">
#        SecRuleInheritance Off
#    </LocationMatch>
#</IfModule>

