# $Id: shell.conf

# Vsite config
Vsite.Shell.enabled                     perl:base/shell/vsite_shell.pl
Vsite.Shell.GoogleAuthentication        perl:base/shell/vsite_gauth.pl

# User config
User._CREATE                            perl:base/shell/user_shell.pl
User.Shell.enabled                      perl:base/shell/user_shell.pl
User.enabled                            perl:base/shell/user_shell.pl

# Jailkit:
System.Jailkit.enabled                  perl:base/shell/jailkit_enabler.pl
Vsite.Shell.enabled                     perl:base/shell/jailkit_enabler.pl
