# Author: Brian N. Smith / Michael Stauber
# Copyright 2007, NuOnce Networks, Inc. & Solarspeed.  All rights reserved.
# $Id: yum.conf

System.yum.update			exec:base/swupdate/yum-update.pl		EXECUTE
System.yum.*				exec:base/swupdate/yum-setting.pl		EXECUTE
System.yum.check			exec:base/swupdate/yum-checker.pl		EXECUTE
System.yum.skiplock			exec:base/swupdate/yum-skiplock.pl		EXECUTE
