# $Id: base-system.conf
# base-system.mod config file

# validate a create
System._CREATE                      perl:base/system/sys_create.pl          VALIDATE

# system locale
System.productLanguage              perl:base/system/product_language.pl    EXECUTE
System.productLanguage              perl:base/system/set_login_locale.pl    EXECUTE
System.locales                      perl:base/system/set_login_locale.pl    EXECUTE

# update /etc/sysconfig/network , /etc/HOSTNAME , handle hostname changes.
System.hostname                     perl:base/system/modsystem.pl           EXECUTE
System.domainname                   perl:base/system/modsystem.pl           EXECUTE
System.gateway                      perl:base/system/modsystem.pl           EXECUTE
System.gateway_IPv6                 perl:base/system/modsystem.pl           EXECUTE
System.nw_update                    perl:base/system/modsystem.pl           EXECUTE

# update /etc/resolv.conf
System.dns                          perl:base/system/etcresolv.pl           EXECUTE
System.domainname                   perl:base/system/etcresolv.pl           EXECUTE
System.nw_update                    perl:base/system/etcresolv.pl           EXECUTE

# enable and disable console:
System.console                      perl:base/system/console.pl             EXECUTE
System._CREATE                      perl:base/system/console.pl             EXECUTE

# MTA Handler
System._CREATE                      perl:base/system/mta.pl                 CONFIGURE
System.MTA                          perl:base/system/mta.pl                 CONFIGURE
System.MTA_update                   perl:base/system/mta.pl                 CONFIGURE

# Mbox handler
System._CREATE                      perl:base/system/mbox.pl                CONFIGURE
System.Mailbox                      perl:base/system/mbox.pl                CONFIGURE
System.Mailbox_update               perl:base/system/mbox.pl                CONFIGURE
System.Mailbox_convert              perl:base/system/mbox_coverter.pl       EXECUTE

# CSRF handling:
System._CREATE                      perl:base/system/csrf.pl                EXECUTE
System.isLicenseAccepted            perl:base/system/csrf.pl                EXECUTE
System.csrf_protection              perl:base/system/csrf.pl                EXECUTE
System.csrf_expire                  perl:base/system/csrf.pl                EXECUTE
System.csrf_regenerate              perl:base/system/csrf.pl                EXECUTE
