#!/bin/sh

IFS=$(echo -en "\n\b")

raids=`mdadm --detail --scan| sort`

for raid in $raids; do 
    array=`echo $raid | awk -F " " '{ print $2 }'` 
    part_array=`echo $raid | awk -F " " '{ print $2 }' | awk -F "/" '{ print $3 }'` 
    level=`echo $raid | awk -F " " '{ print $3 }' | awk -F "raid" '{ print $2 }'` 
    num_devices=`echo $raid | awk -F " " '{ print $4 }' | awk -F "=" '{ print $2 }'`

    mdadm=`mdadm --detail $array`
    
    persistence=`mdadm --detail $array |grep Persistence | awk -F ":" '{ print $2 }'`
    if [ $persistence = " Superblock is persistent" ];then
        superblock="1"
    else
        superblock="0"
    fi

    chunkSize=`mdadm --detail $array |grep "Chunk Size" | awk -F ":" '{ print $2 }' | awk -F "K" '{ print $1 }'`
    if [ !$chunkSize ];then
        chunkSize="0"
    fi
    
    echo "raiddev $array"
    echo -e "\traid-level\t\t$level"
    echo -e "\tnr-raid-disks\t\t$num_devices"
    echo -e "\tpersistent-superblock\t$superblock"
    echo -e "\tchunk-size\t\t$chunkSize"
    for ((disk=0; disk<$num_devices; disk++));do
        part=$(($disk+5))
        member=`cat /proc/mdstat |grep $part_array |awk -F " " '{ print $'$part' }' | awk -F "[" '{ print $1 }'`
        raid_disk=`cat /proc/mdstat |grep $part_array |awk -F " " '{ print $'$part' }' | awk -F "[" '{ print $2 }' | awk -F "]" '{ print $1 }'`
        echo -e "\tdevice\t\t/dev/$member"
        echo -e "\traid-disk\t\t$raid_disk"
    done
done

# 
# Copyright (c) 2008-2022 Michael Stauber, SOLARSPEED.NET
# Copyright (c) 2008-2022 Team BlueOnyx, BLUEONYX.IT
# All Rights Reserved.
# 
# 1. Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
#    notice, this list of conditions and the following disclaimer in 
#    the documentation and/or other materials provided with the 
#    distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its 
#    contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
# You acknowledge that this software is not designed or intended for 
# use in the design, construction, operation or maintenance of any 
# nuclear facility.
# 