

LOG_FILE='/var/log/letsencrypt/letsencrypt.log'
#LOG_LEVEL=1

AUTO_UPGRADE='0'

#NO_TIMESTAMP=1

    
CERT_HOME='/usr/sausalito/acme/certs'
ACCOUNT_KEY_PATH='/usr/sausalito/acme/account.key'
USER_AGENT='BlueOnyx-ACME-Client'
ACCOUNT_EMAIL='apache@localhost'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
