# $Id: schedule.conf

Schedule._CREATE	perl:base/schedule/create.pl	EXECUTE

#
# Call the modify handler for all properties except filename.  No
# handler is specified for the filename property, since it is just
# data, and private data at that.
#
Schedule.enabled			perl:base/schedule/modify.pl	EXECUTE
Schedule.name				perl:base/schedule/modify.pl	EXECUTE
Schedule.start_time			perl:base/schedule/modify.pl	EXECUTE
Schedule.interval			perl:base/schedule/modify.pl	EXECUTE
Schedule.action				perl:base/schedule/modify.pl	EXECUTE

Schedule._DESTROY			perl:base/schedule/delete.pl	EXECUTE

