#
### Proy to map /v2/cce to https://127.0.0.1:9092/v2/cce for access to CCEd-API:
#

SSLProxyEngine On
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyVerify none
SSLProxyVerifyDepth 1

RequestHeader set X-Real-IP %{REMOTE_ADDR}s

ProxyPreserveHost On
ProxyPass /v2/cce https://127.0.0.1:9092/v2/cce
ProxyPassReverse /v2/cce https://127.0.0.1:9092/v2/cce

ProxyPass /v2/metrics https://127.0.0.1:9092/v2/metrics
ProxyPassReverse /v2/metrics https://127.0.0.1:9092/v2/metrics

ProxyPass /v2/services https://127.0.0.1:9092/v2/services
ProxyPassReverse /v2/services https://127.0.0.1:9092/v2/services

