# Just to hold some variables used across E,mail components..

package Email;

use vars qw($VIRTUSER $ACCESS);

$VIRTUSER = '/etc/mail/virtusertable';
$ACCESS = '/etc/mail/access';
$MAILERTABLE = '/etc/mail/mailertable';

# FIXME: rest of these should also be scalars instead of functions
sub Aliases { return '/etc/mail/aliases'; }
sub SendmailCF { return '/etc/mail/sendmail.cf'; }
sub SendmailMC { return '/etc/mail/sendmail.mc'; }
sub SendmailCW { return '/etc/mail/local-host-names'; }

if (-f "/usr/lib/mailman/bin/add_members") {
        sub MajordomoAliases { return '/etc/mail/aliases.mailman'; }
}
if (-f "/usr/local/majordomo/bin/approve") {
        sub MajordomoAliases { return '/etc/mail/aliases.majordomo'; }
}

sub BxrblsFile { return '/etc/sysconfig/bxrbls'; }

# Write /etc/sysconfig/bxrbls for blueonyx-postfix-confgen (no CODB in the shell).
# $skip_oid: omit this dnsbl object (DESTROY handlers).
sub write_bxrbls {
    my ($cce, $skip_oid) = @_;
    return 0 unless $cce;
    $skip_oid ||= 0;

    my $threshold = 1;
    my @sys = $cce->find('System');
    if (@sys) {
        my ($ok, $email) = $cce->get($sys[0], 'Email');
        if ($ok && defined $email->{dnsbl_threshold} && $email->{dnsbl_threshold} =~ /^[0-9]+$/) {
            $threshold = int($email->{dnsbl_threshold});
        }
    }
    $threshold = 1 if $threshold < 1;
    $threshold = 99 if $threshold > 99;

    my @sites;
    foreach my $oid ($cce->find('dnsbl')) {
        next if $skip_oid && $oid == $skip_oid;
        my ($ok, $rbl) = $cce->get($oid);
        next unless $ok && $rbl->{active};
        my $host = $rbl->{blacklistHost} || '';
        $host =~ s/[^A-Za-z0-9._-]//g;
        next unless length $host;
        my $w = 1;
        if (defined $rbl->{weight} && $rbl->{weight} =~ /^[0-9]+$/) {
            $w = int($rbl->{weight});
        }
        $w = 1 if $w < 1;
        $w = 99 if $w > 99;
        push @sites, "$host*$w";
    }

    my $file = BxrblsFile();
    my $body = "# Generated by BlueOnyx. Do not edit.\n"
             . "THRESHOLD=$threshold\n"
             . 'SITES="' . join(',', @sites) . "\"\n";
    my $tmp = $file . '.tmp.' . $$;
    if (open(my $fh, '>', $tmp)) {
        print $fh $body;
        close $fh;
        chmod 0644, $tmp;
        return 1 if rename($tmp, $file);
        unlink $tmp;
    }
    return 0;
}

return 1;
# 
# Copyright (c) 2008-2022 Michael Stauber, SOLARSPEED.NET
# Copyright (c) 2008-2022 Team BlueOnyx, BLUEONYX.IT
# Copyright (c) 2003 Sun Microsystems, Inc. 
# All Rights Reserved.
# 
# 1. Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright 
#    notice, this list of conditions and the following disclaimer in 
#    the documentation and/or other materials provided with the 
#    distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its 
#    contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
# You acknowledge that this software is not designed or intended for 
# use in the design, construction, operation or maintenance of any 
# nuclear facility.
# 