; Global PHP-FPM settings for AdmServ master-pool:
[global]
log_level = warning
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s
daemonize = yes

; Pool name and settings:
[www]
listen = /run/admserv-php-fpm/admserv-php-fpm.sock
listen.owner = admserv
listen.group = admserv
listen.mode = 0666

; UID/GID:
user = admserv
group = admserv

; Set to 'ondemand' and set limits:
pm = ondemand
pm.max_children = 15
pm.process_idle_timeout = 300s
pm.max_requests = 500

; Set session path to a directory owned by process user
php_value[session.save_handler] = files
php_value[session.save_path] = /var/lib/php/session

; Global PHP settings inherited from the main php.ini:
php_admin_flag[register_globals] = Off
php_admin_flag[allow_url_fopen] = Off
php_admin_flag[allow_url_include] = Off
php_admin_value[post_max_size] = 512M
php_admin_value[upload_max_filesize] = 512M
php_admin_value[max_execution_time] = 3000
php_admin_value[max_input_time] = 3000
php_admin_value[memory_limit] = 512M
php_admin_flag[mail.add_x_header] = On
php_value[include_path] = ".:/usr/sausalito/ui/chorizo/ci4/app/Libraries:/usr/sausalito/ui/web"

