#
# $Id: wizard.conf
#
# need to make sure the wizard page has a default
#

System._CREATE                              perl:base/wizard/wizard_splash.pl
System.productLanguage                      perl:base/wizard/wizard_splash.pl
System.Time.timeZone                        perl:base/wizard/timeZoneGui.pl
System.hostname                             perl:base/wizard/serverNameGui.pl
System.domainname                           perl:base/wizard/serverNameGui.pl
System.GUI_PORT                             perl:base/wizard/serverNameGui.pl
System.GUI_URLs                             perl:base/wizard/serverNameGui.pl