#!/usr/bin/expect
# $Id: am_ftp.exp

source /usr/sausalito/swatch/statecodes.tcl

# Messages that Active Monitor maps to localized strings
set env(redMsg)   "amFtpRed"
set env(greenMsg) "amFtpGreen"

# don't echo the dialog
log_user 0

# be defensive about hangs
set timeout 10

# we use telnet to connect
spawn telnet 127.0.0.1 21
expect {
    "Connected to" {}
    default {
        # we don't connect properly -> try restart
        catch {exec systemctl restart xinetd >&/dev/null} result
        sleep 3

        # redo test, fail if error again
        spawn telnet 127.0.0.1 21
        expect {
            "Connected to" {}
            default {
                puts -nonewline $env(redMsg)
                flush stdout
                exit $AM_STATE_RED
            }
        }
    }
}

expect {
    "220 " {}
    default {
        # fail if we're not greeted properly
        puts -nonewline $env(redMsg)
        flush stdout
        exit $AM_STATE_RED
    }
}

send "QUIT\r"
expect {
    "221 " {}
    default {
        # fail if we're not ack-ed properly
        puts -nonewline $env(redMsg)
        flush stdout
        exit $AM_STATE_RED
    }
}

puts -nonewline $env(greenMsg)
flush stdout
exit $AM_STATE_GREEN
